# This file is only used for local development.

version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: personalphotomap-backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "8092:8092"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    container_name: personalphotomap-frontend
    env_file:
      - .env
    environment:
      BACKEND_URL: ${VITE_BACKEND_URL}  
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
